### ISSUE TITLE
Version number mismatch?

### ISSUE THREAD

**Issue by mstevens83** [berndporr/iirj#10]
On the v1.0.5 release page (https://github.com/berndporr/iirj/releases/tag/1.0.5) you mention this is the first version release to maven central, but over there I can only find version 1.0 (https://search.maven.org/#artifactdetails%7Cuk.me.berndporr%7Ciirj%7C1.0%7Cjar).
Is this the same one?
Perhaps you could re-release it to maven central as 1.0.5 to avoid confusion?
Thanks.

**Comment by berndporr** [comment]
Please note the additional digit on github. It's intentional not to have that on maven. If there are any issues then I'd release 1.1 but the 1.0.x stuff is purely cosmetic. See the log. Hope that makes it clear.
Otherwise I need to release every time a different version I fix a mishtake in the README on github...

**Comment by mstevens83** [comment]
Ok, still a bit confusing though :)

**Comment by berndporr** [comment]
At some point might add another digit to it. I was expecting more smaller changes since the release but so far nobody has spotted any bugs... ;)

**Comment by berndporr** [comment]
I've now dropped the last digit. Should be now 1.1 on maven and on github.
