### ISSUE TITLE
Input for butterworth filter on audio signal

### ISSUE THREAD

**Issue by Rohitverma05** [berndporr/iirj#18]
I have an array of  audio signal ranging from nearly -5000 to 5000 and I want to apply a bandpass filter on it. Its a heartbeat audio but I have to filter it .
The array when plotted on a graph looks something like [this](https://imgur.com/a/JmA5nhf)

When I apply filter on this , the result comes out distorted and the frequencies are not filtered. I am suspecting that the array range should be in range of -1 to 1 instead of -5000 to 5000. 
Can anyone tell me what should be the input on the butterworth algo!?

**Comment by berndporr** [comment]
The butterworth filter takes floating point numbers so +/-5000 is fine. Otherwise this comment is not helpful as it's vague and lacks any technical detail (fs, cutoff, expected result). Looks like bug in your program. Of course if you suspect a bug in this library provide a test case and a pull request I can review.
